New New Measure dialog
malloydata/malloy-composer pull request #13
Opened 2022-11-10 19:57 UTC by whscullin

First pass at updated New Measure dialog. For https://github.com/looker-open-source/malloy/issues/604

2022-11-10 21:35 UTC, christopherswenson requested changes
Looks awesome. I have a few comments... but this is also fine as is.

2022-11-10 21:35 UTC, christopherswenson commented on src/app/AddNewMeasure/AddNewMeasure.tsx
> +              rows={3}
Might be nice to add a `min-height` and `resize: vertical` on this `CodeTextArea` element. Otherwise:
<img width="443" alt="Screen Shot 2022-11-10 at 3 07 16 PM" src="https://user-images.githubusercontent.com/3538955/201206879-fe729b44-7790-49dc-8331-90eeb13faa68.png">
<img width="620" alt="Screen Shot 2022-11-10 at 3 07 21 PM" src="https://user-images.githubusercontent.com/3538955/201206868-dd18afa6-c34c-4906-9345-1ca202d1fbc3.png">




Looks like it isn't used anywhere else yet, though we'll probably want to (in a different PR likely) use it in all the places where you edit code.

2022-11-10 21:35 UTC, christopherswenson commented on src/app/AddNewMeasure/AddNewMeasure.tsx
> +                options={fields}
Might be nice to use `FieldButton`s here instead of just a simple dropdown, like we do in every other place where you select a field. Doesn't seem like we have a pre-built component for doing a popover dropdown containing `FieldButton`s, so maybe we should make one. Would just take remixing `SelectDropdown` a bit to allow arbitrary components as options, I think.

Something along these lines:
<img width="465" alt="Screen Shot 2022-11-10 at 3 16 32 PM" src="https://user-images.githubusercontent.com/3538955/201208076-4c20ea5e-dc1b-440b-a482-76826f3f9460.png">

Maybe @tschomer has thoughts.

2022-11-10 21:35 UTC, christopherswenson commented on src/app/AddNewMeasure/AddNewMeasure.tsx
> +                  divider: true,
The spacing of the divider (or lack thereof) looks a touch off to me.
<img width="414" alt="Screen Shot 2022-11-10 at 3 08 17 PM" src="https://user-images.githubusercontent.com/3538955/201208339-d8750f07-fce5-4410-b27a-597596c9839e.png">

```diff
diff --git a/src/app/SelectDropdown/SelectDropdown.tsx b/src/app/SelectDropdown/SelectDropdown.tsx
index 30f5d8b..b02fead 100644
--- a/src/app/SelectDropdown/SelectDropdown.tsx
+++ b/src/app/SelectDropdown/SelectDropdown.tsx
@@ -60,11 +60,7 @@ export const InputBox = styled.div`
   }
 `;
 
-interface OptionDivProps {
-  divider: boolean;
-}
-
-const OptionDiv = styled.label<OptionDivProps>`
+const OptionDiv = styled.label`
   padding: 0px 10px;
   height: 30px;
   cursor: pointer;
@@ -77,7 +73,6 @@ const OptionDiv = styled.label<OptionDivProps>`
   &:hover {
     background-color: ${COLORS.dimension.fillLight};
   }
-  ${({ divider }) => (divider ? "border-top: 1px solid #ececed" : "")}
 `;
 
 const OptionSpan = styled.span`
@@ -163,16 +158,18 @@ export function SelectList<T>({
         const isSelected =
           value !== undefined && valueEqual(value, option.value);
         return (
-          <OptionDiv
-            divider={option.divider}
-            key={index}
-            onClick={() => onChange(option.value)}
-            className={isSelected ? "selected" : ""}
-          >
-            <OptionRadio type="radio" defaultChecked={isSelected} />
-            <CheckIcon className={isSelected ? "selected" : ""} />
-            <OptionSpan>{option.label}</OptionSpan>
-          </OptionDiv>
+          <>
+            {option.divider && <OptionDivider key={"divider" + index} />}
+            <OptionDiv
+              key={index}
+              onClick={() => onChange(option.value)}
+              className={isSelected ? "selected" : ""}
+            >
+              <OptionRadio type="radio" defaultChecked={isSelected} />
+              <CheckIcon className={isSelected ? "selected" : ""} />
+              <OptionSpan>{option.label}</OptionSpan>
+            </OptionDiv>
+          </>
         );
       })}
     </SelectListDiv>
@@ -187,13 +184,12 @@ export function DropdownMenu({ options }: DropdownMenuProps): JSX.Element {
   return (
     <SelectListDiv>
       {options.map((option, index) => (
-        <OptionDiv
-          divider={option.divider}
-          key={index}
-          onClick={() => option.onSelect()}
-        >
-          <OptionSpan>{option.label}</OptionSpan>
-        </OptionDiv>
+        <>
+          {option.divider && <OptionDivider key={"divider" + index} />}
+          <OptionDiv key={index} onClick={() => option.onSelect()}>
+            <OptionSpan>{option.label}</OptionSpan>
+          </OptionDiv>
+        </>
       ))}
     </SelectListDiv>
   );
@@ -214,3 +210,10 @@ const SelectListDiv = styled.div`
   overflow-y: auto;
   max-height: 400px;
 `;
+
+const OptionDivider = styled.div`
+  border-top: 1px solid #ececec;
+  width: 100%;
+  margin: 0 10px;
+  margin: 5px 0;
+`;
```
This diff makes it look like this:
<img width="494" alt="Screen Shot 2022-11-10 at 3 26 43 PM" src="https://user-images.githubusercontent.com/3538955/201209389-82198659-71d3-4e3b-831d-37df6155729b.png">

If you're cool with that I can commit it.

2022-11-10 21:35 UTC, christopherswenson commented on src/app/AddNewMeasure/AddNewMeasure.tsx
> +              placeholder="some_field * 10"
Maybe a slightly less fake placeholder like `count() * items_per_count`

2022-11-10 21:35 UTC, christopherswenson commented on src/app/AddNewMeasure/AddNewMeasure.tsx
> +        setMeasure(`count() / all(count(), \`${field}\`) * 100.0`);
Miiight be nice to factor these measure generators elsewhere, maybe into `core/` somewhere. And maybe abstract out (and stub) the quoting of the field names, with a comment saying `// TODO decide when to quote based on field name`.

There's this function which already exists... https://github.com/malloydata/malloy-composer/blob/main/src/core/query.ts#L663-L671, but it clearly doesn't handle keywords correctly.

2022-11-10 21:42 UTC, whscullin commented on src/app/AddNewMeasure/AddNewMeasure.tsx
> +                  divider: true,
:shipit:

2022-11-11 16:17 UTC, christopherswenson approved these changes

2022-11-11 16:18 UTC, christopherswenson commented
Looks great — I added one more comment, if you want to do that now. Otherwise, :shipit:

2022-11-11 21:57 UTC, merged